#!/bin/bash
# ═══════════════════════════════════════════════════════════════
#  Run all example queries and save output to EXAMPLE_RESULTS.md
#
#  Usage:
#    1. Stop your current server (Ctrl+C)
#    2. bash scripts/run_examples.sh
#
#  This will:
#    - Reseed TypeDB with fresh 16-entity dataset
#    - Start the API server in background
#    - Run all example queries
#    - Save results to EXAMPLE_RESULTS.md
#    - Stop the server
# ═══════════════════════════════════════════════════════════════
set -e

# ── Activate virtual environment ────────────────────────────────
if [ -f ".venv/bin/activate" ]; then
    # shellcheck disable=SC1091
    source .venv/bin/activate
    echo "Using venv Python: $(python3 --version) at $(which python3)"
elif [ -f "venv/bin/activate" ]; then
    # shellcheck disable=SC1091
    source venv/bin/activate
    echo "Using venv Python: $(python3 --version) at $(which python3)"
else
    echo "WARNING: No .venv found. Using system Python: $(python3 --version)"
fi

BASE_URL="http://localhost:8000"
OUTPUT="EXAMPLE_RESULTS.md"
SERVER_PID=""

cleanup() {
    if [ -n "$SERVER_PID" ]; then
        echo ""
        echo "Stopping API server (PID $SERVER_PID)..."
        kill "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT

echo "============================================================"
echo "  Hypergraph Context Graph — Example Runner"
echo "============================================================"
echo ""

# ── Step 1: Reseed database ─────────────────────────────────────
echo "[1/4] Reseeding TypeDB with fresh data (16 entities, 6 decisions, 4 two-morphisms)..."
python3 scripts/setup_typedb.py --seed
echo ""

# ── Step 2: Start server in background ──────────────────────────
echo "[2/4] Starting API server..."
python3 -m uvicorn src.api.main:app --host 0.0.0.0 --port 8000 &
SERVER_PID=$!
echo "  Server PID: $SERVER_PID"
echo "  Waiting for server to start..."
sleep 5

# Verify server is up
if ! curl -s "$BASE_URL/health" > /dev/null 2>&1; then
    echo "  Waiting a bit longer..."
    sleep 5
fi

HEALTH=$(curl -s "$BASE_URL/health")
echo "  Health: $HEALTH"
echo ""

# ── Step 3: Run all queries ─────────────────────────────────────
echo "[3/4] Running example queries..."

# Start markdown file
cat > "$OUTPUT" << 'HEADER'
# Example Results: Context Graph Queries with 2-Morphisms

> Auto-generated by `scripts/run_examples.sh`
> Each query hits the full pipeline: TypeDB → ContextAgent → ExecutiveAgent (Claude) → 2-Morphism Extraction → TypeDB Writeback

---

HEADER

# ── Entities ────────────────────────────────────────────────────
echo "  Fetching entities..."
ENTITIES=$(curl -s "$BASE_URL/api/v1/entities")
ENTITY_COUNT=$(echo "$ENTITIES" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "?")
cat >> "$OUTPUT" << EOF
## Seed Data Loaded

**Entities: $ENTITY_COUNT**

\`\`\`bash
curl -s http://localhost:8000/api/v1/entities | python3 -m json.tool
\`\`\`

\`\`\`json
$(echo "$ENTITIES" | python3 -m json.tool 2>/dev/null || echo "$ENTITIES")
\`\`\`

EOF

# ── Hyperedges ──────────────────────────────────────────────────
echo "  Fetching hyperedges..."
HEDGES=$(curl -s "$BASE_URL/api/v1/hyperedges")
HEDGE_COUNT=$(echo "$HEDGES" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "?")
cat >> "$OUTPUT" << EOF
**Hyperedges: $HEDGE_COUNT**

\`\`\`bash
curl -s http://localhost:8000/api/v1/hyperedges | python3 -m json.tool
\`\`\`

\`\`\`json
$(echo "$HEDGES" | python3 -m json.tool 2>/dev/null || echo "$HEDGES")
\`\`\`

---

EOF

# ── Query function ──────────────────────────────────────────────
run_query() {
    local num="$1"
    local title="$2"
    local query="$3"

    echo "  Query $num: $title"
    RESULT=$(curl -s -X POST "$BASE_URL/api/v1/query" \
        -H "Content-Type: application/json" \
        -d "{\"query\":\"$query\"}")

    # Extract key fields
    ANSWER=$(echo "$RESULT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('answer', 'N/A'))
" 2>/dev/null || echo "Error parsing response")

    PROPOSED=$(echo "$RESULT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('two_morphisms_proposed', 0))
" 2>/dev/null || echo "?")

    STORED=$(echo "$RESULT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('two_morphisms_stored', 0))
" 2>/dev/null || echo "?")

    CONFIDENCE=$(echo "$RESULT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('confidence', 0))
" 2>/dev/null || echo "?")

    PATHS=$(echo "$RESULT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('paths_found', 0))
" 2>/dev/null || echo "?")

    cat >> "$OUTPUT" << EOF
## Query $num: $title

\`\`\`bash
curl -s -X POST http://localhost:8000/api/v1/query \\
  -H "Content-Type: application/json" \\
  -d '{"query":"$query"}' | python3 -m json.tool
\`\`\`

### Claude's Answer

$ANSWER

### Metrics

| Metric | Value |
|---|---|
| Confidence | $CONFIDENCE |
| Paths Found | $PATHS |
| 2-Morphisms Proposed | $PROPOSED |
| 2-Morphisms Stored | $STORED |

<details>
<summary>Full JSON Response</summary>

\`\`\`json
$(echo "$RESULT" | python3 -m json.tool 2>/dev/null || echo "$RESULT")
\`\`\`

</details>

---

EOF

    echo "    → Confidence: $CONFIDENCE | 2-morphisms: $PROPOSED proposed, $STORED stored"
}

# ── Run all queries (with delays to avoid API rate limits) ──────
run_query 1 \
    "Why was the Acme discount approved?" \
    "Why was the Acme discount approved?"

echo "  Waiting 5s (rate limit cooldown)..."
sleep 5

run_query 2 \
    "What precedents exist for above-policy discounts?" \
    "What precedents exist for giving discounts above policy limits?"

echo "  Waiting 5s (rate limit cooldown)..."
sleep 5

run_query 3 \
    "How are Acme, Globex, and Initech connected?" \
    "How are Acme, Globex and Initech decisions connected?"

echo "  Waiting 5s (rate limit cooldown)..."
sleep 5

run_query 4 \
    "What is Sarah Chen's role across all decisions?" \
    "What role does Sarah Chen play across all enterprise decisions and what patterns emerge?"

echo "  Waiting 5s (rate limit cooldown)..."
sleep 5

run_query 5 \
    "Risk of more above-policy discounts?" \
    "What is the risk of continuing to approve discounts above the standard policy limit?"

# ── Final state ─────────────────────────────────────────────────
echo ""
echo "  Fetching final hyperedge count (after feedback loop)..."
FINAL_HEDGES=$(curl -s "$BASE_URL/api/v1/hyperedges")
FINAL_COUNT=$(echo "$FINAL_HEDGES" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "?")

cat >> "$OUTPUT" << EOF
## Graph Growth: Feedback Loop

After running 5 queries, the graph has grown from the original seed data:

**Final hyperedge count: $FINAL_COUNT** (started with 6 seed decisions + 4 seed 2-morphisms)

Each query that proposes new 2-morphisms stores them back to TypeDB (with deduplication).
The next query sees a richer graph and can reason over the compounded decision traces.

> *"The system that wins isn't the one that captures the most context on day one — it's the one that gets better at capturing and delivering context over time."*
> — [Foundation Capital](https://foundationcapital.com/context-graphs-ais-trillion-dollar-opportunity/)
EOF

echo ""
echo "============================================================"
echo "  Done! Results saved to: $OUTPUT"
echo "  Entities: $ENTITY_COUNT"
echo "  Initial hyperedges: $HEDGE_COUNT"
echo "  Final hyperedges: $FINAL_COUNT (after feedback loop)"
echo "============================================================"
